// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBkENX8nAtSQKXaMu6O24tcPkXyRp3QY',
    appId: '1:960666777716:web:4abc481f0de214921b7921',
    messagingSenderId: '960666777716',
    projectId: 'bel3arabiquizapp-fcb56',
    authDomain: 'bel3arabiquizapp-fcb56.firebaseapp.com',
    storageBucket: 'bel3arabiquizapp-fcb56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-zBdmyD2-o9-KVfMaAq0292OTprCekI',
    appId: '1:960666777716:android:8fdbaf7b82d19a781b7921',
    messagingSenderId: '960666777716',
    projectId: 'bel3arabiquizapp-fcb56',
    storageBucket: 'bel3arabiquizapp-fcb56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPvrnM3n-gx2a3EhKEvIS8yEDs6hKvz9s',
    appId: '1:960666777716:ios:35670d86dd28ba301b7921',
    messagingSenderId: '960666777716',
    projectId: 'bel3arabiquizapp-fcb56',
    storageBucket: 'bel3arabiquizapp-fcb56.appspot.com',
    iosBundleId: 'com.example.quizAppWithEman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPvrnM3n-gx2a3EhKEvIS8yEDs6hKvz9s',
    appId: '1:960666777716:ios:8458256e570d0ee91b7921',
    messagingSenderId: '960666777716',
    projectId: 'bel3arabiquizapp-fcb56',
    storageBucket: 'bel3arabiquizapp-fcb56.appspot.com',
    iosBundleId: 'com.example.quizAppWithEman.RunnerTests',
  );
}
